---
title: "beetle_pooloza"
author: "Khum"
date: "2024-08-13"
output: html_document
---

```{r}
library(raster)
library(dplyr)
library(sf)
library(tidyverse)
# library(map)
library(tigris)

```


```{r}
btle<- read.csv("C:/Users/Khum/Downloads/BeetleMeasurements_resized.csv")

btle_meas<- read.csv("C:/Users/Khum/Downloads/BeetleMeasurements.csv")

btle_meta<-read.csv("C:/Users/Khum/Downloads/individual_metadata.csv")
```


```{r}
neon_site<- read.csv("C:/Users/Khum/Downloads/NEON_Field_Site_Metadata_20240813.csv")%>%
  select(field_site_id,field_longitude,field_latitude,field_site_type)%>%
  filter(field_site_type %in% c("Gradient Terrestrial","Core Terrestrial"))

write.csv(neon_site,"C:/Users/Khum/OneDrive - UCB-O365/beetlepooloza/neon_site_gps.csv")
```

## all the rasters data are of 5 minutes resolutions

```{r}
ele<-raster("C:/Users/Khum/Downloads/wc2.1_5m_elev/wc2.1_5m_elev.tif")

ele_msk<-mask(ele,usa)
names(ele_msk) <- "ele_msk"


```

```{r}
path_prep<-"C:/Users/Khum/Downloads/wc2.1_5m_prec"
prep_list<-list.files(path_prep, pattern='tif$', full.names=TRUE)

prep_stk<-stack(prep_list)
prep_mean <- calc(prep_stk, mean)
names(prep_mean) <- "prep_mean"

```


```{r}
path_temp<-"C:/Users/Khum/Downloads/wc2.1_5m_tavg"
temp_list<-list.files(path_temp, pattern='tif$', full.names=TRUE)

temp_stk<-stack(temp_list)
temp_mean <- calc(temp_stk, mean)

names(temp_mean) <- "temp_mean"

```


```{r}


# us <- map_data("state")
usa <- st_as_sf(maps::map("state", fill=TRUE, plot =FALSE))


# states <- states(cb = TRUE)%>%
#   filter(!NAME %in% c("Alaska", "Hawaii","Puerto Rico",
#                       "Commonwealth of the Northern Mariana Islands","Guam","United States Virgin Islands","District of Columbia 
# ","American Samoa","Delaware District of Columbia"))


```


```{r}
current<-stack(ele,prep_mean, temp_mean)

current_msk <- mask(current, usa)

myRaster <- writeRaster(current_msk, "C:/Users/Khum/OneDrive - UCB-O365/beetlepooloza/env_cu.grd", format="raster")


```

## testing the cropped stacked data
```{r}
cu <- stack("C:/Users/Khum/OneDrive - UCB-O365/beetlepooloza/current_msk.grd")
```

```{r}
temp2050<-stack("C:/Users/Khum/Downloads/wc2.1_5m_tmax_IPSL-CM6A-LR_ssp585_2041-2060.tif")

temp_2050mean <- calc(temp2050, mean)


temp2050_msk<- mask(temp_2050mean, usa)

names(temp2050_msk) <- "temp2050_msk"


# writeRaster(temp20250_msk, "C:/Users/Khum/OneDrive - UCB-O365/beetlepooloza/temp20250_msk.grd", format="raster")


prep2050<-stack("C:/Users/Khum/Downloads/wc2.1_5m_prec_IPSL-CM6A-LR_ssp585_2041-2060.tif")


prep_2050mean <- calc(prep2050, mean)


prep2050_msk<- mask(prep_2050mean, usa)

names(prep2050_msk) <- "prep2050_msk"


env_fu<-stack(temp2050_msk,prep2050_msk,ele_msk)


writeRaster(env_fu, "C:/Users/Khum/OneDrive - UCB-O365/beetlepooloza/env_fu.grd", format="raster")

```

## environmental data is ready for the SDMs analysis

```{r}
current<-stack("C:/Users/Khum/OneDrive - UCB-O365/beetlepooloza/env_cu.grd")

future<-stack("C:/Users/Khum/OneDrive - UCB-O365/beetlepooloza/env_fu.grd")

```


```{r}
data<-read.csv("C:/Users/Khum/OneDrive - UCB-O365/beetlepooloza/neon_site_gps.csv")
```

## run the modeling twice for current and future climates

```{r}

library(biomod2)
# Select the name of the studied species
myRespName <- 'melanarius_current'

# Get corresponding presence/absence data
myResp <- as.numeric(data[, 'melanarius'])

# Get corresponding XY coordinates
myRespXY <- data[, c('field_longitude', 'field_latitude')]

myBiomodData <- BIOMOD_FormatingData(resp.var = myResp,
                                     expl.var = current,
                                     resp.xy = myRespXY,
                                     resp.name = myRespName)
myBiomodData
plot(myBiomodData)

# Model single models
myBiomodModelOut <- BIOMOD_Modeling(bm.format = myBiomodData,
                                    modeling.id = 'AllModels',
                                    CV.strategy = 'random',
                                    CV.nb.rep = 2,
                                    CV.perc = 0.8,
                                    var.import = 3,
                                    metric.eval = c('TSS','ROC'))
                                    # seed.val = 123)
                                    # nb.cpu = 8)
myBiomodModelOut
myBiomodEM <- BIOMOD_EnsembleModeling(bm.mod = myBiomodModelOut,
                                      models.chosen = 'all',
                                      em.by = 'all',
                                      em.algo = c('EMmean'),
                                      metric.select = c('TSS'),
                                      metric.eval = c('TSS', 'ROC'),
                                      var.import = 3,
                                      EMci.alpha = 0.05,
                                      EMwmean.decay = 'proportional')
myBiomodEM

# Project single models
myBiomodProj <- BIOMOD_Projection(bm.mod = myBiomodModelOut,
                                  proj.name = 'Current',
                                  new.env = current,
                                  models.chosen = 'all',
                                  metric.binary = 'all',
                                  metric.filter = 'all',
                                  build.clamping.mask = TRUE)
myBiomodProj
plot(myBiomodProj)

# Project ensemble models (building single projections)
myBiomodEMProj <- BIOMOD_EnsembleForecasting(bm.em = myBiomodEM,
                                             proj.name = 'CurrentEM',
                                             new.env = current,
                                             models.chosen = 'all',
                                             metric.binary = 'all',
                                             metric.filter = 'all')

myBiomodEMProj
plot(myBiomodEMProj)

# 
# # Project ensemble models (from single projections)
# myBiomodEMProj <- BIOMOD_EnsembleForecasting(bm.em = myBiomodEM, 
#                                              bm.proj = myBiomodProj,
#                                              models.chosen = 'all',
#                                              metric.binary = 'all',
#                                              metric.filter = 'all')

```


```{r}

library(ggplot2)
future<-raster("C:/Users/Khum/OneDrive - UCB-O365/Beetle_poolaza/code/melanarius/proj_Current/proj_Current_melanarius.tif")

current<-raster("C:/Users/Khum/OneDrive - UCB-O365/Beetle_poolaza/code/melanarius.current/proj_CurrentEM/proj_CurrentEM_melanarius.current_ensemble.tif")

plot(future,xlim=c(-124.6813,-70.00742), ylim=c(25.12993,50.38323))

current_df<-as.data.frame(current, xy=TRUE)%>%
  rename(layer=melanarius.current_EMmeanByTSS_mergedData_mergedRun_mergedAlgo)%>%
  as.data.frame()%>%
  ggplot()+
    geom_raster(mapping=aes(x=x,y=y,fill=layer/1000))
  
  
  Figure1E<-mats_prob%>%
  na.omit()%>%
  ggplot()+
  geom_sf(data=fryxell_aoi$geometry, fill=NA)+
  geom_raster(mapping=aes(x=x,y=y,fill=layer/1000))+
  scale_fill_gradientn(colours=c("darkgreen","yellow","red"))+
  theme(panel.background=element_rect(color="black",fill=NA),
        legend.title=element_blank())+
  labs(x="longitude", y="lattitude")+
  scalebar(x.min = 163.30, x.max = 163.36,
           y.min = -77.64, y.max = -77.65,
           dist = 1, dist_unit = "km", st.color = "black",
           transform = TRUE, model = "WGS84", st.size=2, height=0.05, st.dist=0.1, border.size=0.2)+
  annotation_north_arrow(location = "tl", which_north = "true", 
                         pad_x = unit(0.02, "in"), pad_y = unit(0.1, "in"),
                         height=unit(0.8, "cm"),
                         style = north_arrow_fancy_orienteering)

Figure1
  

```



```{r}
data<- read.csv("C:/Users/Khum/Downloads/evaluation_results (1).csv")%>%
  select(Actual_Label.Name,Short_Names)


data %>%
  pivot_wider(names_from = Actual_Label.Name, values_from = Short_Names)

library(tidyr)
a<-data %>%
  group_by(Actual_Label.Name,Short_Names)%>%
  summarize(value=length(Short_Names))%>%
  mutate(presence=1)%>%
  tidyr::pivot_wider(names_from = Actual_Label.Name, values_from = presence,values_fill = 0)%>%
  select(-value)

write.csv(a,"C:/Users/Khum/OneDrive - UCB-O365/beetlepooloza/bettle.csv")

library(data.table)
df_t <- as.data.frame(transpose(a))
colnames(df_t) <- rownames(a)



```

